kotlin.stdlib.default.dependency=false
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseParallelGC -XX:+AlwaysPreTouch
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
kotlin.incremental=true
kotlin.daemon.jvmargs=-Xmx2048m -XX:+UseParallelGC
org.jetbrains.intellij.platform.testIdeBundledPluginsClasspathEnabled=true
org.jetbrains.intellij.platform.testIdeBundledPluginsClasspathExcludes=org.jetbrains.plugins.vue,com.intellij.openRewrite,com.intellij.ja,com.intellij.ko,com.intellij.zh
